### ISSUE TITLE
Font: Обновление

### ISSUE THREAD

**Issue by burunduk** [NYRDS/pixel-dungeon-remix#12]
Хочу предложить шрифт. Менял много, старался все строчные буквы подогнать под одну ширину. 

![font25x](https://cloud.githubusercontent.com/assets/912818/20675926/a9ad7a5e-b596-11e6-8560-cce61906f423.png)

**Comment by DeadDie44** [comment]
Выглядит вроде неплохо, но надо сначала посмотреть как оно в игре. Как потестим, тогда решим.

**Comment by Mikhael-Danilov** [comment]
Добавил шрифт в бета версию.
Ждём отзывов.

**Comment by burunduk** [comment]
А сложно будет сделать вібор из списка шрифтов, или проще модами менять?

**Comment by Mikhael-Danilov** [comment]
Особой сложности в этом нет. Но думаю нет и необходимости.
Предложенный шрифт явно лучше того что был.

Менять их модами нужно аккуратно ( список символов пока не доступен для моддинга )

**Comment by TerenceCool01** [comment]
Меня буквы т и ш настораживают
т больно на м похожа, а ш вообще на w. А в целом хорошо

**Comment by burunduk** [comment]
Т можно вернуть, согласен. Слишком на рукописный уже смахивает.с ш, убрать скругление? Тогда точно копия w будет.

**Comment by burunduk** [comment]
![font25x](https://cloud.githubusercontent.com/assets/912818/20859360/79882d24-b965-11e6-8326-f61ed2afecca.png)
«т» переделал.
с «ш, щ» убрал скругление.

**Comment by Mikhael-Danilov** [comment]
Итого шрифт принят.

**Comment by burunduk** [comment]
![font25x](https://cloud.githubusercontent.com/assets/912818/20869263/5266e588-ba77-11e6-8229-11ffbd740431.png)
Исправил «т» на строчную и «шщ» убрал сглаживание.
