### ISSUE TITLE
We need get CI to working condition.

### ISSUE THREAD

**Issue by Mikhael-Danilov** [NYRDS/pixel-dungeon-remix#15]

**Comment by burunduk** [comment]
А что дает использования двух систем?
Есть какие то плюшки от этого?

**Comment by Mikhael-Danilov** [comment]
Возможность их сравнить, понять какая из них удобнее.

**Comment by Mikhael-Danilov** [comment]
И скачивать с них готовве сборки...

**Comment by swooboo** [comment]
One project I'm involved in uses Semaphore (example [here](https://semaphoreci.com/red-eclipse/base/branches/master/builds/1347)). What's nice about it, is that it automatically builds each commit, so you don't have to build and deploy each time. @burunduk - which 2 systems are you talking about?

**Comment by Mikhael-Danilov** [comment]
Thanks for Semaphore ( do not know about it before ).
Currently CI builds is done by Travis-CI and CircleCI. But no auto-tests yet, not to mention continuous delivery.

**Comment by swooboo** [comment]
I think it's safe to close this issue. Continuous delivery and automatic tests should come later, and we can open a new issue for these.

**Comment by Mikhael-Danilov** [comment]
Agreed
