### ISSUE TITLE
Распростарнение через F-Droid

### ISSUE THREAD

**Issue by burunduk** [NYRDS/pixel-dungeon-remix#20]
Можете на сервера F-Droid закинуть игрушку?
Или поднять свой отдельный?

**Comment by Mikhael-Danilov** [comment]
Есть небольшая проблемка, сейчас rpd использует несвободные библиотеки (admob, appodeal, etc ), что насколько я знаю на F-Droid не приветствуется. Соответственно нужно готовить отдельную сборку.

Если же проблема только в том чтобы скачивать игрушку без GooglePlay то свежие apk регулярно выкладываются на [вики]( http://wiki.nyrds.net/doku.php?id=ru:rpd:changelog)

**Comment by burunduk** [comment]
А свой сервер поднять, или тоже нельзя?
Это только для автообновления. И, в принципе, не столь важно.

**Comment by Mikhael-Danilov** [comment]
Вот это можно.
https://f-droid.org/wiki/page/Installing_the_Server_and_Repo_Tools

Но когда руки до этого дойдут не знаю.

**Comment by Mikhael-Danilov** [comment]
В ветке MultiBuilds начал разделять стор-специфичные фичи.

**Comment by Poussinou** [comment]
@IzzySoft

**Comment by IzzySoft** [comment]
1. не могу без APK (я не компилироваю)
2. Обычно мой репо не приветствует игры (с некоторыми исключениями для очень небольших приложений)
3. APK слишком большой для моего репозитория

Мне очень жаль, но нет.

**Comment by Poussinou** [comment]
@IzzySoft no problem, I don't know the rules of your repo, but it is useful ;)

**Comment by IzzySoft** [comment]
@Poussinou You can find them [here](https://apt.izzysoft.de/fdroid/index/info) (together with some more background). And glad to read you like it!

**Comment by swooboo** [comment]
Is there any planned / achieved progress of thus issue? I propose canceling / closing depending on the status.

**Comment by IzzySoft** [comment]
@swooboo In its current state, F-Droid probably would refuse due to "proprietary dependencies":

    googlePlayImplementation 'com.google.android.gms:play-services-ads:10.2.1'
    googlePlayImplementation 'com.google.android.gms:play-services-base:10.2.1'
    googlePlayImplementation 'com.google.android.gms:play-services-analytics:10.2.1'
    googlePlayImplementation "com.google.android.gms:play-services-games:10.2.1"

So unless there's a flavor without those, it wouldn't make much sense to apply.

**Comment by swooboo** [comment]
Is somebody working on implementation on such flavour? @Mikhael-Danilov

**Comment by Mikhael-Danilov** [comment]
Not yet.

**Comment by swooboo** [comment]
We can close this for now then? Maybe revisit / reopen later?

**Comment by Mikhael-Danilov** [comment]
Let close it for now.
