### ISSUE TITLE
In German language, i can unequip an unequipped ring. When i do that, the game crashes.

### ISSUE THREAD

**Issue by AntiMatterAMA** [NYRDS/pixel-dungeon-remix#22]
Crash report:

USER_COMMENT=null
ANDROID_VERSION=7.1.1
APP_VERSION_NAME=remix.27.1.fix.1
BRAND=motorola
PHONE_MODEL=XT1092
CUSTOM_DATA=RPD_active_mod = Remixed
selectKind = spritesDesc/TownGuardNPC.json
FreeInternalMemorySize = 827146240
font = true
active_mod_version = 10452
apk signature = Jw5WWI9rrwVRRpDbjoF0b8-TmfE=\n
Locale = de
Bundle read line = {"version":"remix.27.1.fix.1","challenges":0,"hero":{"__className":"com.watabou.pixeldungeon.actors.hero.Hero","time":0,"pos":241,"HP":20,"HT":20,"buffs":[{"__className":"com.watabou.pixeldungeon.actors.buffs.Regeneration","time":7.5},{"__className":"com.watabou.pixeldungeon.actors.buffs.Hunger","time":9.5,"level":0}],"class":"ROGUE","subClass":"NONE","attackSkill":10,"defenseSkill":5,"STR":10,"lvl":1,"exp":0,"levelId":"town","difficulty":3,"pets":[],"sp":0,"quantity":1,"level":0,"levelKnown":false,"cursed":false,"cursedKnown":false,"inventory":[{"__className":"com.watabou.pixeldungeon.items.rings.RingOfShadows","quantity":1,"level":1,"levelKnown":true,"cursed":false,"cursedKnown":true}],"armor":{"__className":"com.watabou.pixeldungeon.items.armor.ClothArmor","quantity":1,"level":0,"levelKnown":true,"cursed":false,"cursedKnown":true}},"gold":100,"depth":0,"potionsOfStrength":0,"scrollsOfEnhancement":0,"arcaneStyli":0,"dewVial":true,"transmutation":14,"chapters":[],"quests":{"sadGhost":{"spawned":false},"wandmaker":{"spawned":false},"blacksmith":{"spawned":false},"demon":{"spawned":false},"azuterron":{"given":false,"depth":0,"processed":false,"completed":false},"scarecrow":{"given":false,"depth":0,"processed":false,"completed":false,"killed":0},"cagedkobold":{"given":false,"depth":0,"processed":false,"completed":false,"spawned":false},"plaguedoctornpc":{"given":false,"depth":0,"processed":false,"completed":false}},"rooms":["MAGIC_WELL","TRAPS","STATUE","TREASURY","WEAK_FLOOR","POOL","WAREHOUSE","STORAGE","CRYPT","ARMORY","VAULT","LIBRARY","GARDEN","LABORATORY"],"score":0,"maxDepth":0,"enemiesSlain":0,"foodEaten":0,"potionsCooked":0,"piranhas":0,"nightHunt":0,"ankhsUsed":0,"duration":2.5,"amuletObtained":false,"journal":[],"class com.watabou.pixeldungeon.items.scrolls.ScrollOfIdentify_image":47,"class com.watabou.pixeldungeon.items.scrolls.ScrollOfIdentify_known":false,"class com.watabou.pixeldungeon.items.scrolls.ScrollOfMagicMapping_image":78,"class com.watabou.pixeldungeon.items.scrolls.ScrollOfMagicMapping_known":true,"class com.watabou.pixeldungeon.items.scrolls.ScrollOfRecharging_image":129,"class com.watabou.pixeldungeon.items.scrolls.ScrollOfRecharging_known":false,"class com.watabou.pixeldungeon.items.scrolls.ScrollOfRemoveCurse_image":46,"class com.watabou.pixeldungeon.items.scrolls.ScrollOfRemoveCurse_known":false,"class com.watabou.pixeldungeon.items.scrolls.ScrollOfTeleportation_image":44,"class com.watabou.pixeldungeon.items.scrolls.ScrollOfTeleportation_known":false,"class com.watabou.pixeldungeon.items.scrolls.ScrollOfUpgrade_image":43,"class com.watabou.pixeldungeon.items.scrolls.ScrollOfUpgrade_known":false,"class com.watabou.pixeldungeon.items.scrolls.ScrollOfChallenge_image":128,"class com.watabou.pixeldungeon.items.scrolls.ScrollOfChallenge_known":false,"class com.watabou.pixeldungeon.items.scrolls.ScrollOfTerror_image":130,"class com.watabou.pixeldungeon.items.scrolls.ScrollOfTerror_known":false,"class com.watabou.pixeldungeon.items.scrolls.ScrollOfLullaby_image":76,"class com.watabou.pixeldungeon.items.scrolls.ScrollOfLullaby_known":false,"class com.watabou.pixeldungeon.items.scrolls.ScrollOfWeaponUpgrade_image":131,"class com.watabou.pixeldungeon.items.scrolls.ScrollOfWeaponUpgrade_known":false,"class com.watabou.pixeldungeon.items.scrolls.ScrollOfPsionicBlast_image":79,"class com.watabou.pixeldungeon.items.scrolls.ScrollOfPsionicBlast_known":false,"class com.watabou.pixeldungeon.items.scrolls.ScrollOfMirrorImage_image":45,"class com.watabou.pixeldungeon.items.scrolls.ScrollOfMirrorImage_known":false,"class com.watabou.pixeldungeon.items.scrolls.ScrollOfDomination_image":77,"class com.watabou.pixeldungeon.items.scrolls.ScrollOfDomination_known":false,"class com.watabou.pixeldungeon.items.scrolls.ScrollOfCurse_image":42,"class com.watabou.pixeldungeon.items.scrolls.ScrollOfCurse_known":false,"class com.watabou.pixeldungeon.items.potions.PotionOfHealing_image":59,"class com.watabou.pixeldungeon.items.potions.PotionOfHealing_known":false,"class com.watabou.pixeldungeon.items.potions.PotionOfExperience_image":57,"class com.watabou.pixeldungeon.items.potions.PotionOfExperience_known":false,"class com.watabou.pixeldungeon.items.potions.PotionOfToxicGas_image":62,"class com.watabou.pixeldungeon.items.potions.PotionOfToxicGas_known":false,"class com.watabou.pixeldungeon.items.potions.PotionOfLiquidFlame_image":60,"class com.watabou.pixeldungeon.items.potions.PotionOfLiquidFlame_known":false,"class com.watabou.pixeldungeon.items.potions.PotionOfStrength_image":61,"class com.watabou.pixeldungeon.items.potions.PotionOfStrength_known":false,"class com.watabou.pixeldungeon.items.potions.PotionOfParalyticGas_image":58,"class com.watabou.pixeldungeon.items.potions.PotionOfParalyticGas_known":false,"class com.watabou.pixeldungeon.items.potions.PotionOfLevitation_image":63,"class com.watabou.pixeldungeon.items.potions.PotionOfLevitation_known":false,"class com.watabou.pixeldungeon.items.potions.PotionOfMindVision_image":65,"class com.watabou.pixeldungeon.items.potions.PotionOfMindVision_known":false,"class com.watabou.pixeldungeon.items.potions.PotionOfPurity_image":64,"class com.watabou.pixeldungeon.items.potions.PotionOfPurity_known":false,"class com.watabou.pixeldungeon.items.potions.PotionOfInvisibility_image":67,"class com.watabou.pixeldungeon.items.potions.PotionOfInvisibility_known":false,"class com.watabou.pixeldungeon.items.potions.PotionOfMight_image":66,"class com.watabou.pixeldungeon.items.potions.PotionOfMight_known":false,"class com.watabou.pixeldungeon.items.potions.PotionOfFrost_image":56,"class com.watabou.pixeldungeon.items.potions.PotionOfFrost_known":false,"class com.watabou.pixeldungeon.items.wands.WandOfTeleportation_image":51,"class com.watabou.pixeldungeon.items.wands.WandOfTeleportation_known":false,"class com.watabou.pixeldungeon.items.wands.WandOfSlowness_image":52,"class com.watabou.pixeldungeon.items.wands.WandOfSlowness_known":false,"class com.watabou.pixeldungeon.items.wands.WandOfFirebolt_image":71,"class com.watabou.pixeldungeon.items.wands.WandOfFirebolt_known":false,"class com.watabou.pixeldungeon.items.wands.WandOfPoison_image":49,"class com.watabou.pixeldungeon.items.wands.WandOfPoison_known":false,"class com.watabou.pixeldungeon.items.wands.WandOfRegrowth_image":68,"class com.watabou.pixeldungeon.items.wands.WandOfRegrowth_known":false,"class com.watabou.pixeldungeon.items.wands.WandOfBlink_image":54,"class com.watabou.pixeldungeon.items.wands.WandOfBlink_known":false,"class com.watabou.pixeldungeon.items.wands.WandOfLightning_image":53,"class com.watabou.pixeldungeon.items.wands.WandOfLightning_known":false,"class com.watabou.pixeldungeon.items.wands.WandOfAmok_image":69,"class com.watabou.pixeldungeon.items.wands.WandOfAmok_known":false,"class com.watabou.pixeldungeon.items.wands.WandOfTelekinesis_image":48,"class com.watabou.pixeldungeon.items.wands.WandOfTelekinesis_known":false,"class com.watabou.pixeldungeon.items.wands.WandOfFlock_image":50,"class com.watabou.pixeldungeon.items.wands.WandOfFlock_known":false,"class com.watabou.pixeldungeon.items.wands.WandOfDisintegration_image":70,"class com.watabou.pixeldungeon.items.wands.WandOfDisintegration_known":false,"class com.watabou.pixeldungeon.items.wands.WandOfAvalanche_image":55,"class com.watabou.pixeldungeon.items.wands.WandOfAvalanche_known":false,"class com.watabou.pixeldungeon.items.rings.RingOfMending_image":38,"class com.watabou.pixeldungeon.items.rings.RingOfMending_known":false,"class com.watabou.pixeldungeon.items.rings.RingOfDetection_image":73,"class com.watabou.pixeldungeon.items.rings.RingOfDetection_known":false,"class com.watabou.pixeldungeon.items.rings.RingOfShadows_image":39,"class com.watabou.pixeldungeon.items.rings.RingOfShadows_known":true,"class com.watabou.pixeldungeon.items.rings.RingOfPower_image":36,"class com.watabou.pixeldungeon.items.rings.RingOfPower_known":false,"class com.watabou.pixeldungeon.items.rings.RingOfHerbalism_image":32,"class com.watabou.pixeldungeon.items.rings.RingOfHerbalism_known":false,"class com.watabou.pixeldungeon.items.rings.RingOfAccuracy_image":34,"class com.watabou.pixeldungeon.items.rings.RingOfAccuracy_known":false,"class com.watabou.pixeldungeon.items.rings.RingOfEvasion_image":72,"class com.watabou.pixeldungeon.items.rings.RingOfEvasion_known":false,"class com.watabou.pixeldungeon.items.rings.RingOfSatiety_image":35,"class com.watabou.pixeldungeon.items.rings.RingOfSatiety_known":false,"class com.watabou.pixeldungeon.items.rings.RingOfHaste_image":74,"class com.watabou.pixeldungeon.items.rings.RingOfHaste_known":false,"class com.watabou.pixeldungeon.items.rings.RingOfHaggler_image":75,"class com.watabou.pixeldungeon.items.rings.RingOfHaggler_known":false,"class com.watabou.pixeldungeon.items.rings.RingOfElements_image":33,"class com.watabou.pixeldungeon.items.rings.RingOfElements_known":false,"class com.watabou.pixeldungeon.items.rings.RingOfThorns_image":37,"class com.watabou.pixeldungeon.items.rings.RingOfThorns_known":false,"badges":{"badges":[]}}

STACK_TRACE=com.nyrds.android.util.TrackedRuntimeException: trying unequip unequipped artifact
	at com.watabou.pixeldungeon.items.rings.Artifact.doUnequip(Artifact.java:61)
	at com.watabou.pixeldungeon.items.EquipableItem.doUnequip(EquipableItem.java:98)
	at com.watabou.pixeldungeon.items.EquipableItem.execute(EquipableItem.java:41)
	at com.watabou.pixeldungeon.windows.WndItem$1.onClick(WndItem.java:74)
	at com.watabou.noosa.ui.Button$1.onClick(Button.java:54)
	at com.watabou.noosa.TouchArea.onSignal(TouchArea.java:82)
	at com.watabou.noosa.ui.Button$1.onSignal(Button.java:63)
	at com.watabou.noosa.ui.Button$1.onSignal(Button.java:38)
	at com.watabou.utils.Signal.dispatch(Signal.java:76)
	at com.watabou.input.Touchscreen.processTouchEvents(Touchscreen.java:74)
	at com.watabou.noosa.Game.update(Game.java:454)
	at com.watabou.noosa.Game.step(Game.java:426)
	at com.watabou.noosa.Game.onDrawFrame(Game.java:359)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1548)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1259)

--  |----------------------------|
--  |•AntiMatterAMA•|
--  |_________________|

**Comment by Mikhael-Danilov** [comment]
Thank You for report.
Bug confirmed.

Turns out ACDrop and ACUnequip share same translation and internally they used for actions ids.

  <string name="Item_ACDrop">ABLEGEN</string>
  <string name="EquipableItem_ACEquip">AUSRÜSTEN</string>
  <string name="EquipableItem_ACUnequip">ABLEGEN</string>

Can you suggest different words in German for "drop" and "unequip" actions ?

**Comment by Mikhael-Danilov** [comment]
Item_ACDrop -> FALLEN LASSEN
EquipableItem_ACUnequip -> AUSZIEHEN
