### ISSUE TITLE
Compass points to town shop in the town level

### ISSUE THREAD

**Issue by swooboo** [NYRDS/pixel-dungeon-remix#27]
I tried fixing this in the config, but I didn't consider that it would break saves. 

Just putting this here, I'm going to try fix this.

**Comment by swooboo** [comment]
Quoting @Mikhael-Danilov :

> Proper way to achieve stated target is to:
> a) Add something like Compass.setTarget(int cell)
> b) Set it using level-parameter or level-script (in case of script compass can be updated for example during quest progress)

**Comment by swooboo** [comment]
I filed the pull request - https://github.com/NYRDS/pixel-dungeon-remix/pull/28

I didn't use level scripts (didn't find enough info on how to do it), but the functionality I added
will probably make integration with level scripts for setting compass easier.

**Comment by swooboo** [comment]
@Mikhael-Danilov, commit 88b0045cfb70be87fbaa85ac6d2b1c99c270906c re-introduced this issue. I think it's safe to re-add this line to `Town.json`:

```
"compassTarget": [26, 29],
```

**Comment by Mikhael-Danilov** [comment]
Agreed
