### ISSUE TITLE
Un-fork this repository

### ISSUE THREAD

**Issue by swooboo** [NYRDS/pixel-dungeon-remix#31]
Currently the repo is in the state 'Forked from...', I think it's time to make this repo standalone. Reasons:

1. This is no longer a 'real' fork of Watabou's PD.
2. Search in the code is disabled for forked repos.
3. While giving credit to Watabou is important, there is already enough credit in the code etc.

To achieve this, it's needed to delete the repo and create a new one, and push the local copy to it. Precise instructions here:

https://stackoverflow.com/questions/29326767/unfork-a-github-fork-without-deleting/41486339#41486339

**Comment by Mikhael-Danilov** [comment]
Not sure if we should do this right now.

But if we do, we will follow
https://stackoverflow.com/a/27718433

So issues, pull requests and all forks of this repo will be preserved.

**Comment by swooboo** [comment]
You're right, that is one of the answers in the first SO link I provided. I'm also not sure it should be done right now. If we don't decide now, I'm going to close this and it can be re-opened for discussion later. For clarity, the solution is to contact GitHub support here - https://github.com/contact .

**Comment by swooboo** [comment]
I guess it's not the time to proceed with this yet. I'm closing this and it can be revisited later on.
