### ISSUE TITLE
Feature suggestion: add a game log in the "journal" GUI

### ISSUE THREAD

**Issue by swooboo** [NYRDS/pixel-dungeon-remix#34]
Currently, the game log is visible in the bottom left corner, but once the messages disappear from it, there is no way to see them.

I suggest to add another tab to the "Journal" GUI, so the older messages can be read from it. 

If we decide to follow through with it, I might try to implement this, but since it's quite complicated at first glance, I might not be able to do it.

**Comment by swooboo** [comment]
Scratch that, I'm already working on this feature. You can see my progress here - https://github.com/swooboo/pixel-dungeon-remix/tree/swooboo-game-log 

It already mostly works, there is a new tab that shows up to 30 last messages.

For now I'm struggling with 3 things:

1. The log book needs to scroll down until the end once opened, but if I make it scroll, it scrolls the levels tab as well, which is inconvenient. It also does this if the log book is opened and scrolled, the other tab scrolls as well.
1. IMO it will be nice to store these log messages so they are not deleted after the game is saved.
1. Are there colors in the GameLog pane? If so, currently the tab doesn't show the colors.

Thoughts?

P.S. Let me know if I commit too many times. I think good practice is to commit atomic changes, but I might have gone overboard this time.

**Comment by swooboo** [comment]
I've dealt with the scrolling and I think it's ready for a pull request so we can close this issue. Next steps (I'll open a new issue for them):

1. Add store / load so it's preserved and not lost upon game load.
1. Add colors like in the GameLog pane.
1. I suspect that some log entries are too long and will require a multiline text, but I couldn't get multiline text to work. (Couldn't set maxWidth in the constructor because there is no width yet)

**Comment by Mikhael-Danilov** [comment]
This indeed will be useful feature.
Atomic commits are best.
For multi-line text you can just call maxWidth when width is known.

**Comment by Mikhael-Danilov** [comment]
I added coloring and save & restore for logbook.
