### ISSUE TITLE
Do not store l10n strings stored in static fields.

### ISSUE THREAD

**Issue by Mikhael-Danilov** [NYRDS/pixel-dungeon-remix#37]
If we get rid of this we will be able to change l10ns and mods without app restart.

**Comment by swooboo** [comment]
Can you explain more for me please? I don't know what l10n is...

**Comment by Mikhael-Danilov** [comment]
Localization. 
Strings for different languages now stored in static fields, so to change game language we have to restart app.

**Comment by swooboo** [comment]
I don't think it's a huge issue that a restart is needed. Most games / apps / programs demand a restart upon language change. My concern after the proposed fix is implemented is that some things will be missed and the game will need to be restarted anyway.

**Comment by swooboo** [comment]
How much work is this and what exactly should be done? If it's simple I'll start working on it. But we need to freeze the files for development so others don't add strings there while we work on this.

**Comment by Mikhael-Danilov** [comment]
This a relatively big piece of work, but I not yet decided how exactly to do it. So for now when I touch class I just inline all fields which used once. But sometimes I decide to allow gui related classes to take not only string but also string id.

Again: this not specific task, but some sort of guide how to write new and refactor old code.

**Comment by swooboo** [comment]
Can you give examples of 'bad' and 'good' lines of code so I know for future? If I understand correctly, all the strings that should be displayed should be put into the separate strings?

**Comment by Mikhael-Danilov** [comment]
Take a look at 69b90102fc8f8ab09c9ee081c4ff3bffc66a8524

**Comment by swooboo** [comment]
Oh, got it, thanks. I will hopefully remember this. Some concerns:

1. Performance - calling `Game::getVar()` each time instead of loading a static string - do you think this is an issue? I looked at the code, it does a `Map.containsKey(), Map.get()`, and there is also `try catch` exception handling which might also impact performance. My concern is that if all the strings are replaced, there will be a lot more such calls.
1. Readability - I'm not sure if the new way is better or worse, but it changes the style and the length of the lines that will be changed.

**Comment by Mikhael-Danilov** [comment]
1. I believe this will not cause any significant performance issues (Strings requested mostly to show ui elements with relatively long (many frames) lifecycle )
2. It is not getting worse and overall code size will be smaller.

**Comment by swooboo** [comment]
Please take a look at [this branch](https://github.com/NYRDS/pixel-dungeon-remix/compare/master...swooboo:swooboo-static-fields). Is this how you want the code to look like? If so I'll continue continue with this. It looks like an easy task, with relatively high ROI.

Currently there are [at least] 42 such files in `src/main/java/com/nyrds/pixeldungeon/` :

```
sergey@LAPTOP-MTTH2AS7:/mnt/c/Users/sergey/Documents/pixel-dungeon-remix$ grep 'private static final String' -r -l PixelDungeon/src/main/java/com/nyrds/pixeldungeon/
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/items/artifacts/CandleOfMindVision.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/items/chaos/ChaosCrystal.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/items/common/armor/NecromancerArmor.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/items/common/armor/NecromancerRobe.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/items/necropolis/BlackSkull.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/items/necropolis/BlackSkullOfMastery.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/levels/IceCavesBossLevel.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/levels/NecroBossLevel.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/levels/objects/PortalGateSender.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/levels/objects/Sign.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/mechanics/buffs/Pain.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/mechanics/spells/Spell.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/mechanics/spells/SpellHelper.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/mechanics/spells/SummoningSpell.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/mobs/common/ArmoredStatue.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/mobs/common/GoldenStatue.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/mobs/common/MultiKindMob.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/mobs/common/ShadowLord.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/mobs/guts/MimicAmulet.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/mobs/guts/SuspiciousRat.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/mobs/icecaves/KoboldIcemancer.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/mobs/npc/AzuterronNPC.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/mobs/npc/BellaNPC.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/mobs/npc/CagedKobold.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/mobs/npc/HealerNPC.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/mobs/npc/LibrarianNPC.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/mobs/npc/NecromancerNPC.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/mobs/npc/PlagueDoctorNPC.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/mobs/npc/ScarecrowNPC.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/mobs/npc/SociologistNPC.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/mobs/npc/TownGuardNPC.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/mobs/npc/TownsfolkMovieNPC.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/mobs/npc/TownsfolkNPC.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/mobs/npc/TownsfolkSilentNPC.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/support/Iap.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/support/OwnAds.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/support/PlayGames.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/utils/DungeonGenerator.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/utils/Position.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/windows/WndFortuneTeller.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/windows/WndMovieTheatre.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/windows/WndPortalWarning.java
PixelDungeon/src/main/java/com/nyrds/pixeldungeon/windows/WndSadGhostNecro.java
sergey@LAPTOP-MTTH2AS7:/mnt/c/Users/sergey/Documents/pixel-dungeon-remix$     
```

**Comment by Mikhael-Danilov** [comment]
Yes, code will end looking something like it, but not as in this example.
Only strings which displayed to player should be obtained through Game.getVar
CHARGES and ACTIVATES - is just fields names for [de]serialization, they should not be translated

**Comment by swooboo** [comment]
Great, sorry about that. I'll remove this commit from the PR. Is there a general rule by which I can determine whether a string is displayed to the player? Or just reading the code?

**Comment by Mikhael-Danilov** [comment]
(Almost) All ui strings already obtained through Game.getVar call. Only exception is strings from wip features, but they should be outside of this PR scope.

**Comment by swooboo** [comment]
Also consider this line - https://github.com/NYRDS/pixel-dungeon-remix/blob/6cef55b97385d5697087ebf6fa517bd677f4fe12/PixelDungeon/src/main/java/com/watabou/pixeldungeon/Assets.java#L40

Should it be moved too? Currently the `R.string.Assets_Prefix` points to an empty string so I'm not sure whether this can change over time. I can think of only one reason to move it - to align with the other usages.

**Comment by Mikhael-Danilov** [comment]
Yes, this line to, but likely it should be replaced with a method.
Also, this string is not empty for Russian and Ukrainian translations

**Comment by Mikhael-Danilov** [comment]
[ResultDescriptions](https://github.com/NYRDS/pixel-dungeon-remix/blob/6611f3c22a5902265fb72c60673ca3c4bf287d3d/PixelDungeon/src/main/java/com/watabou/pixeldungeon/ResultDescriptions.java) : getDescription(String) method is better option in my opinion

**Comment by swooboo** [comment]
1. `BANNERS_PREFIX` - For now I've just replaced it with the `Game.getVar()` call.
2. Death descriptions - OK, but what would it return when an unknown type is provided? Do you think "Died under mysterious circumstances on level %d" is good?

**Comment by Mikhael-Danilov** [comment]
2. It will be great!

**Comment by swooboo** [comment]
OK now trying to add the reason to `strings_results.xml` - what do I add in the other languages? Can I not add them? Or should empty strings be added?

**Comment by Mikhael-Danilov** [comment]
Just add it to strings_results.xml.
Then I upload it to transifex, and eventually people will translate it.

**Comment by swooboo** [comment]
Done. #54 incorporates all the remaining cases that I could find. Any ideas on how to make sure there are no others?

**Comment by swooboo** [comment]
So after some playing around, I've changed this:

https://github.com/NYRDS/pixel-dungeon-remix/blob/17d47d33e92f786517cad2f4bdb027ab06a57491/PixelDungeon/src/main/java/com/watabou/pixeldungeon/PixelDungeon.java#L345-L349

To this:

```java
	public static void uiLanguage(String lang) {
		Preferences.INSTANCE.put(Preferences.KEY_LOCALE, lang);

		instance().setSelectedLanguage();
		instance().resetScene();
	}
```

And it worked! No restart required and all the strings were translated!

**Comment by Mikhael-Danilov** [comment]
As intended ;)
But from cb82e0ba3fc386751c38797e968745bc39f36464 and below we get a bunch of magic strings ("Mob","Boss" and so on) scattered through codebase. 
Would you please replace them with public enum in ResultDesciption ?

**Comment by swooboo** [comment]
Done

**Comment by Mikhael-Danilov** [comment]
Confirmed
