### ISSUE TITLE
Town portal can be activated, but doesn't work

### ISSUE THREAD

**Issue by swooboo** [NYRDS/pixel-dungeon-remix#38]
In my current run, I think I activated all the portals in the dungeon (or maybe not - how many are there?), now the one on level 0 (the town) can be activated, but it doesn't levelport anywhere. 

IMO, it should do one of the following:

1. Disable the activation if it can't bring the player anywhere
1. Levelport the player to the lowest portal in the dungeon
1. Let the player choose which portal to teleport to

This is because right now it's useless, albeit it seems like it should do something, since touching it makes it animate.

**Comment by Mikhael-Danilov** [comment]
There is  six of them.

Behavior as described definitely a bug.
Correct behavior should be as you described in 1.

Can you please describe how to reproduce this issue?

**Comment by swooboo** [comment]
I will try to reproduce it from scratch. For now, what I can gather from my warrior run:

1. Running warrior
1. Maximum depth is 15
1. All portals up to this point are already used
1. Going to the town portal activates it
1. Can't enter the portal

**Comment by Mikhael-Danilov** [comment]
Thanks! Looks like this info is enough to fix town portal.
