### ISSUE TITLE
L18n: неправильно построенное предложение.

### ISSUE THREAD

**Issue by Arex-rus** [NYRDS/pixel-dungeon-remix#4]
https://github.com/NYRDS/pixel-dungeon-remix/blob/master/res/values-ru/strings.xml#L1151
Здесь неверно употреблён деепричастный оборот. Если исходить из правил русского языка, то получается, что в данном предложении палочка сама себя использует в качестве оружия. :+1:) 
В общем, предлагаю убрать деепричастный оборот, и сделать что-то вроде "При использовании в качестве оружия ближнего боя эта палочка  нанесёт %d урона за удар." или ещё короче – без "при использовании".

**Comment by Mikhael-Danilov** [comment]
Речь идет о фразе:
   <string name="Wand_Damage">Используя эту палочку в качестве оружия ближнего боя, она нанесёт %d урона за удар.</string>

( сслыка уехала )

**Comment by Arex-rus** [comment]
Да, имелась в виду именно эта строчка. Похоже, я случайно нажал не туда.
В общем, я бы написал так: "В качестве оружия ближнего боя эта палочка нанесёт %d урона за удар."

Кстати, ещё на несколько строк ниже неправильный перевод.
https://github.com/NYRDS/pixel-dungeon-remix/blob/master/res/values-ru/strings.xml#L1184
"Purpleheart" переводится не как "лиловая", так как это прилагательное описывает, как палочка выглядит, а в остальных случаях - названия древесины, из которой она состоит. Так что в данном случае должно быть "амарантовая" (смотри https://ru.wikipedia.org/wiki/Амарант_(древесина) ).

**Comment by Arex-rus** [comment]
Да и вообще, я со вчерашнего дня вычитал уже почти три четверти файла strings.xml. В основном много ошибок с запятыми, орфографических поменьше, довольно часто несогласованность членов предложения. Ошибки перевода почти не трогал, лишь там, где слишком уж бросались в глаза.
В общем, когда закончу, могу выслать файл с исправлениями на почту или залить куда-нибудь, как будет удобнее.

**Comment by Mikhael-Danilov** [comment]
Огромное Спасибо!
Самым удобным вариантом будет pull request.

**Comment by Arex-rus** [comment]
Вроде бы сделал на добавление коммита. Не уверен только, что правильно, никогда этим не занимался.

**Comment by Mikhael-Danilov** [comment]
Всё получилось правильно
