### ISSUE TITLE
Setup travis to publish signed auto-builds in github releases.

### ISSUE THREAD

**Issue by Mikhael-Danilov** [NYRDS/pixel-dungeon-remix#40]

**Comment by Mikhael-Danilov** [comment]
Done but with bitrise instead of travis

**Comment by swooboo** [comment]
Can you show what's done please @Mikhael-Danilov . Sorry I've been out of the loop lately.

**Comment by Mikhael-Danilov** [comment]
Sorry for late reply.
I setup CI for RPD using [Bitrise](https://www.bitrise.io?referrer=b33d83985559b5e6)
Configuration of build mostly done in gui manner, but I added config file to repo:
https://github.com/NYRDS/pixel-dungeon-remix/blob/28.1/bitrise.yml

**Comment by swooboo** [comment]
Thanks! Is the product of Bitrise run visible to outside? What exactly will be executed by it?

**Comment by Mikhael-Danilov** [comment]
Test builds and Google Play releases.
