### ISSUE TITLE
NEW LOGO FOR U

### ISSUE THREAD

**Issue by abdulmalikkhan655** [NYRDS/pixel-dungeon-remix#42]
Hello ,@NYRDS  I want contribute to pixel-dungeon-remix r so i designed a new logo for pixel-dungeon-remixit's free.

I hope you like it. If you like it, I will send you pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.

if you want i will send you my designed

**Comment by Mikhael-Danilov** [comment]
New logo? Could you show me it?

**Comment by abdulmalikkhan655** [comment]
hello sir check this logo and select your logo If there's something you want to change, I'll do it.

![screenshot_6](https://user-images.githubusercontent.com/36396753/39801700-83836ac6-5385-11e8-92d4-338bb5f8231e.png)

**Comment by Mikhael-Danilov** [comment]
Thanks for your effort but this logos do not fit to Remixed design style.

**Comment by Mikhael-Danilov** [comment]
Please check Remixed page on [Google Play](https://play.google.com/store/apps/details?id=com.nyrds.pixeldungeon.ml)

**Comment by abdulmalikkhan655** [comment]
thats cool sir you check my new logo for your application  select your logo If there's something you want to change, I'll do it.
![32149083_1860345770677163_3658649259529469952_n](https://user-images.githubusercontent.com/36396753/39851501-92e21994-5430-11e8-85c5-ef97e95f8b10.jpg)
![32151059_1860345477343859_8861907812561715200_n](https://user-images.githubusercontent.com/36396753/39851502-9365647a-5430-11e8-8d9c-27ae24c75b6c.jpg)

**Comment by abdulmalikkhan655** [comment]
thats cool sir you check my new logo for your application select your logo
If there's something you want to change, I'll do it.

**Comment by abdulmalikkhan655** [comment]
hello @Mikhael-Danilov   sir any updates ??

**Comment by Mikhael-Danilov** [comment]
Sorry for late answer.
Those logos are out of style, sorry for any time wasted.
