### ISSUE TITLE
CODEBEAT not working

### ISSUE THREAD

**Issue by swooboo** [NYRDS/pixel-dungeon-remix#49]
I always see this on my PRs - "_Pending_ - 9 issues resolved and 22 introduced", and CODEBEAD is not running. I think you said something earlier but I forgot. 

@Mikhael-Danilov can you disable it until solution so we have a clearer picture?

**Comment by Mikhael-Danilov** [comment]
This definitely something wrong with codebeat integration but it still send updates by mail. I think we can just ignore it for some time.

**Comment by swooboo** [comment]
OK then, closing.
